from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["no_bump_allowed"]
pre_bump_hooks = [
    "echo Bumping in cog is not allowed, please use release-plz to bump versions",
    "exit 1",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[ cargo fmt ]"
just cargo-fmt-check

echo "[ typos ]"
typos

echo "[ typos $1 ]"
typos $1

echo "[ just machete ]"
just machete

echo "[ cog verify ]"
cog verify --file $1
"""

[changelog]
path = ""
template = ""
remote = ""
repository = ""
owner = ""
authors = []

[commit_types]

[bump_profiles]
